name: Deploy & Build

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone & Install packages
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
     
          script: |
            source ./venv/bin/activate
            git clone git@github.com-repo-0:NeMaksym/ibooks-export-be.git
            pip install -r requirements.txt
